package ncc;
import java.awt.print.*;
import java.sql.*;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * -----------------------------------------------------------------------------
 *  Copyright-Gaurav Jain 
 * THIS APPLICATION IS MADE FOR  3(BENGAL)TECH AIR SQN NCC , IIT KHARAGPUR
 * BY GAURAV JAIN (12MT10013), 1st YEAR STUDENT, IIT KHARAGPUR.
 * -----------------------------------------------------------------------------
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gaurav Jain
 */
public class start extends javax.swing.JFrame {

    /**
     * Creates new form start
     */
    public start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        op = new javax.swing.JOptionPane();
        jFrame1 = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        yr1 = new javax.swing.JRadioButton();
        yr2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        msg = new javax.swing.JLabel();
        dat = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        flt = new javax.swing.JTextField();
        iitrno = new javax.swing.JTextField();
        regt1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ts = new javax.swing.JLabel();
        ps = new javax.swing.JLabel();
        as = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        atdlbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        plbl = new javax.swing.JLabel();
        plbl1 = new javax.swing.JLabel();
        plbl2 = new javax.swing.JLabel();
        yr3 = new javax.swing.JRadioButton();
        yr4 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbm = new javax.swing.JComboBox();
        cby = new javax.swing.JComboBox();
        date = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        plb = new javax.swing.JLabel();
        alb = new javax.swing.JLabel();
        tlb = new javax.swing.JLabel();
        drd = new javax.swing.JRadioButton();
        mrd = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nnd = new javax.swing.JLabel();
        pnd = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        yr5 = new javax.swing.JRadioButton();
        regt2 = new javax.swing.JTextField();
        iitrno1 = new javax.swing.JTextField();
        yr6 = new javax.swing.JRadioButton();
        flt1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblg = new javax.swing.JTable();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        pwd1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        op.setAutoscrolls(true);

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setTitle("CMS-3(B) Tech NCC Air Sqdn.");
        jFrame1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jFrame1.setMinimumSize(new java.awt.Dimension(703, 656));
        jFrame1.setPreferredSize(new java.awt.Dimension(723, 656));

        jPanel9.setBackground(new java.awt.Color(204, 204, 255));
        jPanel9.setMinimumSize(new java.awt.Dimension(723, 656));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ncc/NCC1.jpg"))); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTabbedPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(703, 373));
        jTabbedPane1.setOpaque(true);

        jPanel2.setMinimumSize(new java.awt.Dimension(483, 233));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Attendence for Date :-");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 15, -1, -1));

        jLabel12.setText("Please Enter the Year of Cadet");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 38, -1, -1));

        buttonGroup1.add(yr1);
        yr1.setSelected(true);
        yr1.setText("1st Year");
        jPanel2.add(yr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 34, -1, -1));

        buttonGroup1.add(yr2);
        yr2.setText("2nd Year");
        jPanel2.add(yr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 34, -1, -1));

        jButton2.setText("Mark Present");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 161, -1, -1));

        msg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 202, 436, 20));

        dat.setEditable(false);
        jPanel2.add(dat, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 12, 133, -1));

        buttonGroup3.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("FLIGH NO.");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 64, -1, -1));

        buttonGroup3.add(jRadioButton3);
        jRadioButton3.setText("IIT ROLL NO.");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 89, -1, -1));

        buttonGroup3.add(jRadioButton4);
        jRadioButton4.setText("REGIMENTAL NO.");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 120, -1, -1));

        flt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fltActionPerformed(evt);
            }
        });
        jPanel2.add(flt, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 64, 91, -1));

        iitrno.setEnabled(false);
        iitrno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iitrnoActionPerformed(evt);
            }
        });
        jPanel2.add(iitrno, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 90, 91, -1));

        regt1.setEnabled(false);
        regt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regt1ActionPerformed(evt);
            }
        });
        jPanel2.add(regt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 121, 91, -1));

        jTabbedPane1.addTab("Attendence", jPanel2);

        jButton8.setText("Refresh");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel5.setText("Ist Year");

        t1.setText("Total Strength");

        p1.setText("Present Sterngth");

        a1.setText("Non Effective strength");

        jLabel10.setText("2nd Year");

        jLabel11.setText("Squadron Report");

        ts.setText("Total Strength");

        ps.setText("Present Sterngth");

        as.setText("Non Effective strength");

        t2.setText("Total Strength");

        p2.setText("Present Sterngth");

        a2.setText("Non Effective strength");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a1)
                            .addComponent(t1)
                            .addComponent(p1))
                        .addGap(340, 340, 340)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t2)
                            .addComponent(p2)
                            .addComponent(a2)
                            .addComponent(jLabel10))))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ts)
                    .addComponent(as)
                    .addComponent(ps)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton8)
                        .addComponent(jLabel11)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(t1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t2)
                            .addComponent(jButton8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a2)))
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(ts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ps)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(as)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reports", jPanel1);

        jPanel3.setMinimumSize(new java.awt.Dimension(696, 343));
        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atdlbl.setText("Today's Attendence Report");
        jPanel3.add(atdlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Year", "Flight NO.", "Cadet no.", "IIT Roll No.", "Regimental No.", "Name", "Attendence"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl);
        tbl.getColumnModel().getColumn(0).setPreferredWidth(10);
        tbl.getColumnModel().getColumn(1).setPreferredWidth(10);
        tbl.getColumnModel().getColumn(2).setPreferredWidth(20);
        tbl.getColumnModel().getColumn(3).setPreferredWidth(30);
        tbl.getColumnModel().getColumn(4).setPreferredWidth(40);
        tbl.getColumnModel().getColumn(5).setPreferredWidth(50);
        tbl.getColumnModel().getColumn(6).setPreferredWidth(10);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 457, 301));

        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 43, -1, -1));

        jButton4.setText("Present's List");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 145, -1, -1));

        jButton5.setText("Absent's List");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 145, -1, -1));

        jButton6.setText("Total Attendence");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 116, -1, -1));

        plbl.setText("Present Student's :-");
        jPanel3.add(plbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 194, 124, -1));

        plbl1.setText("Absent Student's :-");
        jPanel3.add(plbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 214, 124, -1));

        plbl2.setText("Total Student's :-");
        jPanel3.add(plbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 174, 124, -1));

        buttonGroup2.add(yr3);
        yr3.setText("2nd Year");
        jPanel3.add(yr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 68, -1, -1));

        buttonGroup2.add(yr4);
        yr4.setSelected(true);
        yr4.setText("1st Year");
        jPanel3.add(yr4, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 68, -1, -1));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("Combined");
        jPanel3.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 91, -1, -1));

        jTabbedPane1.addTab("Today's Report", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Find Attendence of Date:- ");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 73, -1, -1));

        cbm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "July", "Aug", "Sept", "Oct", "Nov", "Dec" }));
        jPanel4.add(cbm, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 93, -1, -1));

        cby.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));
        jPanel4.add(cby, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 93, -1, -1));
        jPanel4.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 93, 34, -1));

        jButton7.setText("Total Attendence List");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        plb.setText("Present Student's :-");
        jPanel4.add(plb, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 131, 128, -1));

        alb.setText("Absent Student's:-");
        jPanel4.add(alb, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 156, 128, -1));

        tlb.setText("Total Student's:-");
        jPanel4.add(tlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 181, 128, -1));

        buttonGroup4.add(drd);
        drd.setSelected(true);
        drd.setText("Day Wise");
        drd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drdActionPerformed(evt);
            }
        });
        jPanel4.add(drd, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 32, -1, -1));

        buttonGroup4.add(mrd);
        mrd.setText("Progressive Report");
        mrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrdActionPerformed(evt);
            }
        });
        jPanel4.add(mrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 22, 12, 207));

        jLabel1.setText("Total no. of days:-");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel2.setText("Total present students:-");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel4.add(nnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 82, 46, 14));
        jPanel4.add(pnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 114, 46, 14));

        jTabbedPane1.addTab("Previous Reports", jPanel4);

        jPanel5.setMinimumSize(new java.awt.Dimension(565, 201));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setText("Get Report");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 141, -1, -1));

        buttonGroup5.add(yr5);
        yr5.setText("2nd Year");
        jPanel5.add(yr5, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 7, -1, -1));

        regt2.setEnabled(false);
        jPanel5.add(regt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 100, 91, -1));

        iitrno1.setEnabled(false);
        jPanel5.add(iitrno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 69, 91, -1));

        buttonGroup5.add(yr6);
        yr6.setSelected(true);
        yr6.setText("1st Year");
        jPanel5.add(yr6, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 7, -1, -1));
        jPanel5.add(flt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 38, 91, -1));

        jLabel13.setText("Please Enter the Year of Cadet");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 11, -1, -1));

        buttonGroup6.add(jRadioButton5);
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("FLIGH NO.");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 37, -1, -1));

        buttonGroup6.add(jRadioButton6);
        jRadioButton6.setText("IIT ROLL NO.");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 68, -1, -1));

        buttonGroup6.add(jRadioButton7);
        jRadioButton7.setText("REGIMENTAL NO.");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 100, -1, -1));

        jLabel8.setText("No of days");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 37, -1, -1));

        jLabel14.setText("No. of Days Present");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 57, -1, -1));

        jLabel15.setText("No. of days absent");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 77, -1, -1));

        jLabel16.setText("perentage of attendence");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 97, -1, -1));

        jTabbedPane1.addTab("Indivisual Report", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setText("Print");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 59, -1, -1));

        jButton11.setText("A (80 and above)");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 93, -1, -1));

        jButton12.setText("B(70 - 79)");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 122, -1, -1));

        jButton13.setText("C(60-69)");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 156, -1, -1));

        jButton14.setText("D(50-59)");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 190, -1, -1));

        jButton15.setText("F(Below 50)");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 224, -1, -1));

        tblg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Yr", "Flight No", "Cadet no.", "Regimental no.", "IIT Roll no.", "Name", "Percentage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblg);
        tblg.getColumnModel().getColumn(0).setMaxWidth(50);
        tblg.getColumnModel().getColumn(1).setMaxWidth(50);
        tblg.getColumnModel().getColumn(2).setMaxWidth(100);
        tblg.getColumnModel().getColumn(6).setMaxWidth(200);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 489, 321));

        buttonGroup7.add(jRadioButton8);
        jRadioButton8.setSelected(true);
        jRadioButton8.setText("1st Year");
        jPanel6.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 11, -1, -1));

        buttonGroup7.add(jRadioButton9);
        jRadioButton9.setText("2nd Year");
        jPanel6.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 11, -1, -1));

        jTabbedPane1.addTab("GRADE", jPanel6);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CMS - 3 (B) Tech Air Sqn NCC");
        setAlwaysOnTop(true);
        setName("start"); // NOI18N

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pwd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwd1ActionPerformed(evt);
            }
        });

        jLabel3.setText("ENTER THE PASSWORD");

        jLabel6.setIcon(new javax.swing.ImageIcon("H:\\NCC\\suryakiranNew.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(pwd1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(pwd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
static int i =0,p=0,t=0;
    @SuppressWarnings("static-access")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String pwd = new String(pwd1.getPassword());

        if(pwd.equals("techair")){
           op.showMessageDialog(this,"Welcome");
            dispose();  
           jFrame1.setVisible(true);
           flt.requestFocusInWindow();
         Calendar c = Calendar.getInstance();
         int iday = c.get(Calendar.DAY_OF_WEEK);
         String day;
         switch(iday){
             case 1: day = "Sunday";    break;
             case 2: day = "Monday";    break;
             case 3: day = "Tuesday";   break;
             case 4: day = "Wednesday"; break;
             case 5: day = "Thursday";  break;
             case 6: day = "Friday";    break;
             case 7: day = "Saturday";  break;
             default : day="";
         }
         String date1=""+c.get(Calendar.DATE)+"-"+(c.get(Calendar.MONTH)+1)+"-"+c.get(Calendar.YEAR);
         dat.setText(date1+","+day);
        
         int ch1 = op.showConfirmDialog(this,"Do You Want To Take Attendence For Today i.e. "+date1+" ?");
            if(ch1 == op.NO_OPTION||ch1 ==op.CANCEL_OPTION){
            jButton2.setEnabled(false);
            jRadioButton2.setEnabled(false);
            jRadioButton3.setEnabled(false);
            jRadioButton4.setEnabled(false);
            flt.setEnabled(false);
            iitrno.setEnabled(false);
            regt1.setEnabled(false);
            yr1.setEnabled(false);
            yr2.setEnabled(false);
            dat.setEnabled(false);
            jPanel1.requestFocusInWindow();
            }
            else{
         try{ 
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ncc","root","root");
            Statement stmt = con.createStatement();
            stmt.execute("Alter Table atd ADD(D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+" char(1) Default 'A' Not Null);");
            stmt.execute("COMMIT");    
            stmt.close();
                con.close();
        }
        catch(Exception econ){
            op.showMessageDialog(this,econ,"Connection Problem",0);
            jButton2.setEnabled(false);
           jRadioButton2.setEnabled(false);
            jRadioButton3.setEnabled(false);
            jRadioButton4.setEnabled(false);
            flt.setEnabled(false);
            iitrno.setEnabled(false);
            regt1.setEnabled(false);
            yr1.setEnabled(false);
            yr2.setEnabled(false);
            dat.setEnabled(false);
            jButton6.doClick();
        }
                    
        }
        }
        else{
            if(i<3){
                op.showMessageDialog(this,"Wrong Passsword Retry Left :"+(3-i),"ERROR",0);
                i++;
                pwd1.setText("");
            }else{
                op.showMessageDialog(this,"Retry Over, Pprogram terminating","Retry over",2);
                System.exit(1);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pwd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwd1ActionPerformed
jButton1.doClick(100);        // TODO add your handling code here:
    }//GEN-LAST:event_pwd1ActionPerformed

    @SuppressWarnings("static-access")
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Calendar c = Calendar.getInstance();
        int yr=1,fltno=0,flag=0,cdtno=0;
        String iitrn,regtno;
        if(jRadioButton2.isSelected()){
        if(yr1.isSelected()) {
            yr=1;
        }
        else {
            yr=2;
        }
        try{
        fltno = Integer.parseInt(flt.getText());
        flag=1;
        cdtno = fltno%100;
        fltno/=100;
        }
        catch(Exception e){
            op.showMessageDialog(this,"Please Enter a Numeric Value","Mismatch Datatype",2);
        op.requestFocusInWindow();
        flt.setText("");
        }}
        iitrn=iitrno.getText();
        regtno = regt1.getText();
            if(flag==1){
         try{ 
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ncc","root","root");
            Statement stmt = con.createStatement();
            ResultSet rs;
            if(jRadioButton2.isSelected()){
            stmt.executeUpdate("Update atd SET D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+"= 'P' Where fltno = "+fltno+"&& yr = "+yr+" && cdtno = "+cdtno+";");
            flt.setText("");
            flt.requestFocusInWindow();
            msg.setText("Attendence Updated for Flight No. "+fltno+"Cadet No."+cdtno);}
            else{
                if(jRadioButton3.isSelected()){
            stmt.executeUpdate("Update atd SET D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+"= 'P' Where iit = \""+iitrn+"\";");
            iitrno.setText("");
            iitrno.requestFocusInWindow();
            msg.setText("Attendence Updated for IIT ROLLNO:-"+iitrn+".");
                }else{                    
            stmt.executeUpdate("Update atd SET D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+"= 'P' Where regtno =\""+regtno+"\";");
            regt1.setText("");
            regt1.requestFocusInWindow();
            msg.setText("Attendence Updated for Regt no. ="+regtno+".");
                }
            }
            rs = stmt.executeQuery("Select Count(*) from atd;");
            rs.first();
            int ttl = rs.getInt(1);
            plbl2.setText("Total Students :- "+ttl);
            rs = stmt.executeQuery("Select Count(*) from atd where D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+"='P';");
            rs.first();
            int pre = rs.getInt(1);
            plbl.setText("Present Student :- "+pre);
            plbl1.setText("Absent Student:-"+(ttl-pre));
            stmt.execute("Commit");    
            stmt.close();
            con.close();
            jButton6.doClick();
            jButton8.doClick();
        }
        catch(Exception econ){
            op.showMessageDialog(this,econ,"Connection Problem",0);
        }
            }
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    @SuppressWarnings("static-access")
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Calendar c = Calendar.getInstance();
        DefaultTableModel tm = (DefaultTableModel) tbl.getModel();
        for(;tm.getRowCount()!=0;){
            tm.removeRow(0);}
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ncc","root","root");
            Statement stmt = con.createStatement();
            ResultSet rs;
            if(yr4.isSelected()){
            rs = stmt.executeQuery("Select yr,fltno,cdtno,iit,regtno,name,D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+" from atd where yr=1 order by fltno,cdtno;");
            }else{
                if(yr3.isSelected()){
                    rs = stmt.executeQuery("Select yr,fltno,cdtno,iit,regtno,name,D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+" from atd where yr=2 order by fltno,cdtno;");
                }
                else{
                    rs = stmt.executeQuery("Select yr,fltno,cdtno,iit,regtno,name,D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+" from atd order by yr,fltno,cdtno;");
                }
            }
            while(rs.next()){
                Object[] newrow = {rs.getInt(1),rs.getInt(2),rs.getInt(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)};
                tm.addRow(newrow);}
            
            if(yr4.isSelected()){
            rs = stmt.executeQuery("Select Count(*) from atd where yr = 2;");
            }else{
                if(yr3.isSelected()){
            rs = stmt.executeQuery("Select Count(*) from atd where yr = 2;");
                }
                else{
     rs = stmt.executeQuery("Select Count(*) from atd;");
                       }
            }
            rs.first();
            int ttl = rs.getInt(1);
            plbl2.setText("Total Students :- "+ttl);
            if(yr4.isSelected()){            
            rs = stmt.executeQuery("Select Count(*) from atd where D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+"='P' && yr=1;");
            }else{
                if(yr3.isSelected()){
            rs = stmt.executeQuery("Select Count(*) from atd where D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+"='P' && yr=2;");
                }
                else{ 
                    rs = stmt.executeQuery("Select Count(*) from atd where D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+"='P';");
           
                       }
            }
            rs.first();
            int pre = rs.getInt(1);
            plbl.setText("Present Student :- "+pre);
            plbl1.setText("Absent Student:-"+(ttl-pre));
            stmt.execute("Commit");
            stmt.close();
            con.close();
        }
        catch(Exception e){   op.showMessageDialog(this,e,"Connection Problem",0);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Calendar c = Calendar.getInstance();
        DefaultTableModel tm = (DefaultTableModel) tbl.getModel();
        for(;tm.getRowCount()!=0;){
            tm.removeRow(0);}
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ncc","root","root");
            Statement stmt = con.createStatement();
            ResultSet rs;
            if(yr4.isSelected()){
                    rs = stmt.executeQuery("Select yr,fltno,cdtno,iit,regtno,name,D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+" from atd  where D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+"='P' && yr=1 order by yr,fltno,cdtno;");
            }else{
                if(yr3.isSelected()){
                    rs = stmt.executeQuery("Select yr,fltno,cdtno,iit,regtno,name,D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+" from atd  where D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+"='P' && yr=2 order by yr,fltno,cdtno;");
                }
                else{
                    rs = stmt.executeQuery("Select yr,fltno,cdtno,iit,regtno,name,D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+" from atd  where D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+"='P' order by yr,fltno,cdtno;");
                }
            }
            while(rs.next()){
                Object[] newrow = {rs.getInt(1),rs.getInt(2),rs.getInt(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)};
                tm.addRow(newrow);}
            stmt.execute("Commit");
            stmt.close();
            con.close();
        }
        catch(Exception e){   JOptionPane.showMessageDialog(this,e,"Connection Problem",0);
        }// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    @SuppressWarnings("static-access")
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Calendar c = Calendar.getInstance();
        DefaultTableModel tm = (DefaultTableModel) tbl.getModel();
        for(;tm.getRowCount()!=0;){
            tm.removeRow(0);}
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ncc","root","root");
            Statement stmt = con.createStatement();
            ResultSet rs;
            
            if(yr4.isSelected()){
                    rs = stmt.executeQuery("Select yr,fltno,cdtno,iit,regtno,name,D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+" from atd  where D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+"='A' && yr=1 order by yr,fltno,cdtno;");
            }else{
                if(yr3.isSelected()){
                    rs = stmt.executeQuery("Select yr,fltno,cdtno,iit,regtno,name,D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+" from atd  where D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+"='A' && yr=2 order by yr,fltno,cdtno;");
                }
                else{
                    rs = stmt.executeQuery("Select yr,fltno,cdtno,iit,regtno,name,D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+" from atd  where D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+"='A' order by yr,fltno,cdtno;");
                }
            }
            while(rs.next()){
                Object[] newrow = {rs.getInt(1),rs.getInt(2),rs.getInt(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)};
                tm.addRow(newrow);}
            stmt.execute("Commit");
            stmt.close();
            con.close();
        }
        catch(Exception e){   op.showMessageDialog(this,e,"Connection Problem",0);
        }// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   try{tbl.print();
        }
   catch(PrinterException e){
   System.out.println(e);
   } 
//   // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void mrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrdActionPerformed
        if(mrd.isSelected()){
            cby.setEnabled(false);            
            cbm.setEnabled(false);
            date.setEnabled(false);
            
}// TODO add your handling code here:
    }//GEN-LAST:event_mrdActionPerformed

    private void drdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drdActionPerformed
         if(drd.isSelected()){
             cby.setEnabled(true);
             cbm.setEnabled(true);
             date.setEnabled(true);}
            //O add your handling code here:
    }//GEN-LAST:event_drdActionPerformed

    private void fltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fltActionPerformed
jButton2.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_fltActionPerformed

    private void iitrnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iitrnoActionPerformed
jButton2.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_iitrnoActionPerformed

    private void regt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regt1ActionPerformed
jButton2.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_regt1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
flt.setText(""); 
    iitrno.setText("");
            regt1.setText("");  
            yr1.setEnabled(false);
            yr2.setEnabled(false);
        iitrno.setEnabled(true);    
        flt.setEnabled(false);
            regt1.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
flt.setText(""); 
    iitrno.setText("");
            regt1.setText("");  
            yr1.setEnabled(false);
            yr2.setEnabled(false);
            iitrno.setEnabled(false);
           regt1.setEnabled(true);
            flt.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
flt.setText(""); 
    iitrno.setText("");
            regt1.setText("");  
            yr1.setEnabled(true);
            yr2.setEnabled(true);
        iitrno.setEnabled(false);  
         flt.setEnabled(true); 
         regt1.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    @SuppressWarnings("static-access")
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int flag=0,d=-1,m=-1,yr,days,j=0,num=0;
        if(drd.isSelected()){
            try{
                d = Integer.parseInt(date.getText());
            }
            catch(Exception ex){
                op.showMessageDialog(null,"Please Enter a Valid Numerical Value in Date Field");
            }
            m = cbm.getSelectedIndex()+1;
            yr = cby.getSelectedIndex()+2012;

            if(d>0 && d<32 && m>0 && m<13){
                if(m==2) {
                    if (yr%4==0 && yr%100!=0){
                        if(d<30) {
                            flag=1;
                        }
                    }
                    else{
                        if(d<29){
                            flag=1;
                        }
                    }
                }
                else{
                    if(m==1||m==3||m==5||m==7||m==8||m==10||m==12){
                        flag=1;
                    }
                    else{
                        if(d<31) {
                            flag=1;
                        }
                    }
                }
            }}
            else{
                if(mrd.isSelected()){
                    if(m>0&&m<13){
                        flag=1;
                    }
                }
            }
            if(flag==1||mrd.isSelected()){
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ncc","root","root");
                    Statement stmt = con.createStatement();
                    ResultSet rs;
                    if(drd.isSelected()){
                    rs = stmt.executeQuery("Select Count(*) from atd;");
                    rs.first();
                    int ttl = rs.getInt(1);
                    tlb.setText("Total Students :- "+ttl);
                        rs = stmt.executeQuery("Select Count(*) from atd where D"+date.getText()+"_"+(cbm.getSelectedIndex()+1)+"_"+(cby.getSelectedIndex()+2012)+"='P';");
                        rs.first();
                        int pre = rs.getInt(1);
                        plb.setText("Present Student :- "+pre);
                        alb.setText("Absent Student:-"+(ttl-pre));
                        
                    }else{
                        if(mrd.isSelected()){
                       rs = stmt.executeQuery("desc atd;");
                       rs.last();
                       days = (rs.getRow()-6);
                       nnd.setText(""+days);
                       String daynam[] = new String[days];
                       rs.absolute(6);
                       while(j<days && rs.next()){
                           daynam[j]=rs.getString("Field");
                           System.out.println("daynam = "+daynam[j]+"day = "+days+" j = "+j);
                       j++;
                       }
                      
                       while(j>0){
                      j--;
                           rs = stmt.executeQuery("Select count("+daynam[j]+") from atd where "+daynam[j]+"='P';");
                       rs.first();
                       num += rs.getInt(1);
                      
                        }
                       pnd.setText(""+num);
                    }

                    }
                    stmt.execute("Commit");
                    stmt.close();
                    con.close();
                }
                catch(Exception e){
                    op.showMessageDialog(this,e,"Connection Problem",0);
                }
            }
            else{
                op.showMessageDialog(this,"This is not a Valid Date. Please Enter A Valid Date");
            }// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    @SuppressWarnings("static-access")
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
Calendar c = Calendar.getInstance();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ncc","root","root");
            Statement stmt = con.createStatement();
            ResultSet rs;
            {
            rs = stmt.executeQuery("Select Count(*) from atd where yr=1;");
            rs.first();
            int ttl = rs.getInt(1);
            t1.setText("Total Strength :- "+ttl);
            rs = stmt.executeQuery("Select Count(*) from atd where D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+"='P' && yr=1;");
            rs.first();
            int pre = rs.getInt(1);
            p1.setText("Present Strength :- "+pre);
            a1.setText("Non Effective Strength:-"+(ttl-pre));
            }
                {
            rs = stmt.executeQuery("Select Count(*) from atd where yr = 2;");
            rs.first();
            int ttl = rs.getInt(1);
            t2.setText("Total Strength :- "+ttl);
            rs = stmt.executeQuery("Select Count(*) from atd where D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+"='P' && yr=2;");
            rs.first();
            int pre = rs.getInt(1);
            p2.setText("Present Strength :- "+pre);
            a2.setText("Non Effective Strength:-"+(ttl-pre));
                }
                {
     rs = stmt.executeQuery("Select Count(*) from atd;");
            rs.first();
            int ttl = rs.getInt(1);
            ts.setText("Total Strength:- "+ttl);
                    rs = stmt.executeQuery("Select Count(*) from atd where D"+c.get(Calendar.DATE)+"_"+(c.get(Calendar.MONTH)+1)+"_"+c.get(Calendar.YEAR)+"='P';");
            rs.first();
            int pre = rs.getInt(1);
            ps.setText("Present Strength:- "+pre);
            as.setText("Non Effective Strength:-"+(ttl-pre));
                       }
            
            stmt.execute("Commit");
            stmt.close();
            con.close();
        }
        catch(Exception e){   op.showMessageDialog(this,e,"Connection Problem",0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    @SuppressWarnings("static-access")
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       int days,num=0,j=0,fltno=0,cdtno=0,yr=0;
       String iitrn="";
       String regtno="";
                   jLabel8.setText("No. of Days:- ");
                   jLabel14.setText("No. of Days present:- ");
                   jLabel15.setText("No. of days absent:- ");
                   jLabel16.setText("Percentage of Attendence:- ");
                  
       if(jRadioButton5.isSelected()){
       try{    if(yr5.isSelected()){
               yr=2;
           }else{
               yr=1;
           }
           fltno = Integer.parseInt(flt1.getText());
           cdtno=fltno%100;
           fltno = fltno/100;}
       catch(Exception e){
           op.showMessageDialog(this,"Please Enter a Valid Numeric Value.");
       }
       }else{try{
           if(jRadioButton6.isSelected()){
               iitrn= iitrno1.getText();
           }else{
               regtno = regt2.getText();
           }
       }
       catch(Exception e){
           op.showMessageDialog(this,"Please Enter a valid value");
       }
       }
        try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ncc","root","root");
                    Statement stmt = con.createStatement();
                    ResultSet rs;
                   
                       rs = stmt.executeQuery("desc atd;");
                       rs.last();
                       days = (rs.getRow()-6);
                       
                       String daynam[] = new String[days];
                       rs.absolute(6);
                       while(j<days && rs.next()){
                           daynam[j]=rs.getString("Field");
                           System.out.println("daynam = "+daynam[j]+"day = "+days+" j = "+j);
                       j++;
                       }
                      
                       while(j>0){
                      j--;
                      if(jRadioButton5.isSelected()){
                           rs = stmt.executeQuery("Select count("+daynam[j]+") from atd where "+daynam[j]+"='P' && fltno = "+fltno+" && cdtno = "+cdtno+"&& yr = "+yr+";");
                     
                      iitrno1.setText("");
                      iitrno1.requestFocusInWindow();}
                      else{
                          if(jRadioButton6.isSelected()){
                      rs = stmt.executeQuery("Select count("+daynam[j]+") from atd where "+daynam[j]+"='P' && iit = \""+iitrn+"\";");         
                          flt1.setText("");
                      flt1.requestFocusInWindow(); }else{
                      rs = stmt.executeQuery("Select count("+daynam[j]+") from atd where "+daynam[j]+"='P' && regtno = \""+regtno+"\";");         
                          regt2.setText("");
                      regt2.requestFocusInWindow();     
                          }
                      }
                          rs.first();
                      
                       num += rs.getInt(1);
                      
                        }
                  
                   jLabel8.setText("No. of Days:- "+days);
                   jLabel14.setText("No. of Days present:- "+num);
                   jLabel15.setText("No. of days absent:- "+(days-num));
                   jLabel16.setText("Percentage of Attendence:- "+(float)(((num*1.0)/days)*100.0)+"%");
                   stmt.execute("Commit");
                    stmt.close();
                    con.close();
                }
                catch(Exception e){
                    op.showMessageDialog(this,e,"Connection Problem",0);
                }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
flt1.setText("");
regt2.setText("");
iitrno1.setText("");
yr5.setEnabled(true);
yr6.setEnabled(true);
        flt1.setEnabled(true);
        regt2.setEnabled(false);
        iitrno1.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
flt1.setText("");
regt2.setText("");
iitrno1.setText("");
yr5.setEnabled(false);
yr6.setEnabled(false);
iitrno1.setEnabled(true);
regt2.setEnabled(false);
flt1.setEnabled(false);// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
flt1.setText("");
regt2.setText("");
iitrno1.setText("");
yr5.setEnabled(false);
yr6.setEnabled(false);
regt2.setEnabled(true);
flt1.setEnabled(false);
iitrno1.setEnabled(false);// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    @SuppressWarnings("static-access")
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       int days,num,j=0;
       double per;
       DefaultTableModel tm = (DefaultTableModel) tblg.getModel();
       tm.setRowCount(0);
       String txt = "Select yr,fltno,cdtno,regtno,iit,name";
        try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ncc","root","root");
                    Statement stmt = con.createStatement();
                    ResultSet rs;
                   
                       rs = stmt.executeQuery("desc atd;");
                       rs.last();
                       days = (rs.getRow()-6);
                       
                       String daynam[] = new String[days];
                       rs.absolute(6);
                       while(j<days && rs.next()){
                           daynam[j]=rs.getString("Field");
                           txt = txt+","+ daynam[j] ;
                       j++;
                       }
                       if(jRadioButton8.isSelected()){
                       txt+=" from atd where yr=1;";}
                       else{
                       txt+=" from atd where yr=2;";}    
                       
                       rs = stmt.executeQuery(txt);
                      while(rs.next()){
                       j=0;num=0;
                       while(j<days){
                      if((rs.getString((++j)+6)).equals("P")) {
                               num++;
                           }
                                          
                        }
                       per = (num*100.0)/days;
                       if((per>=60.00)&&(per<70.00)){
                          Object obj[]={rs.getInt(1),rs.getInt(2),rs.getInt(3),rs.getString(4),rs.getString(5),rs.getString(6),per};
                          tm.addRow(obj);
                       }
                          
                      }
                   stmt.execute("Commit");
                    stmt.close();
                    con.close();
                }
                catch(Exception e){
                    op.showMessageDialog(this,e,"Connection Problem",0);
                }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            tblg.print();  
            // TODO add your handling code here:
        } catch (PrinterException ex) {
            Logger.getLogger(start.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      int days,num,j=0;
       double per;
       DefaultTableModel tm = (DefaultTableModel) tblg.getModel();
       tm.setRowCount(0);
       String txt = "Select yr,fltno,cdtno,regtno,iit,name";
        try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ncc","root","root");
                    Statement stmt = con.createStatement();
                    ResultSet rs;
                   
                       rs = stmt.executeQuery("desc atd;");
                       rs.last();
                       days = (rs.getRow()-6);
                       
                       String daynam[] = new String[days];
                       rs.absolute(6);
                       while(j<days && rs.next()){
                           daynam[j]=rs.getString("Field");
                           txt = txt+","+ daynam[j] ;
                       j++;
                       }
                        if(jRadioButton8.isSelected()){
                       txt+=" from atd where yr=1;";}
                       else{
                       txt+=" from atd where yr=2;";}    
                       rs = stmt.executeQuery(txt);
                      while(rs.next()){
                       j=0;num=0;
                       while(j<days){
                      if((rs.getString((++j)+6)).equals("P")) {
                               num++;
                           }
                                          
                        }
                       per = (num*100.0)/days;
                       if((per>=80.00)&&(per<100.01)){
                          Object obj[]={rs.getInt(1),rs.getInt(2),rs.getInt(3),rs.getString(4),rs.getString(5),rs.getString(6),per};
                          tm.addRow(obj);
                       }
                          
                      }
                   stmt.execute("Commit");
                    stmt.close();
                    con.close();
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(this,e,"Connection Problem",0);
                }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    @SuppressWarnings("static-access")
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
int days,num,j=0;
       double per;
       DefaultTableModel tm = (DefaultTableModel) tblg.getModel();
       tm.setRowCount(0);
       String txt = "Select yr,fltno,cdtno,regtno,iit,name";
        try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ncc","root","root");
                    Statement stmt = con.createStatement();
                    ResultSet rs;
                   
                       rs = stmt.executeQuery("desc atd;");
                       rs.last();
                       days = (rs.getRow()-6);
                       
                       String daynam[] = new String[days];
                       rs.absolute(6);
                       while(j<days && rs.next()){
                           daynam[j]=rs.getString("Field");
                           txt = txt+","+ daynam[j] ;
                       j++;
                       }
                        if(jRadioButton8.isSelected()){
                       txt+=" from atd where yr=1;";}
                       else{
                       txt+=" from atd where yr=2;";}    
                       rs = stmt.executeQuery(txt);
                      while(rs.next()){
                       j=0;num=0;
                       while(j<days){
                      if((rs.getString((++j)+6)).equals("P")) {
                               num++;
                           }
                                          
                        }
                       per = (num*100.0)/days;
                       if((per>=70.00)&&(per<80.00)){
                          Object obj[]={rs.getInt(1),rs.getInt(2),rs.getInt(3),rs.getString(4),rs.getString(5),rs.getString(6),per};
                          tm.addRow(obj);
                       }
                          
                      }
                   stmt.execute("Commit");
                    stmt.close();
                    con.close();
                }
                catch(Exception e){
                    op.showMessageDialog(this,e,"Connection Problem",0);
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    @SuppressWarnings("static-access")
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
int days,num,j=0;
       double per;
       DefaultTableModel tm = (DefaultTableModel) tblg.getModel();
       tm.setRowCount(0);
       String txt = "Select yr,fltno,cdtno,regtno,iit,name";
        try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ncc","root","root");
                    Statement stmt = con.createStatement();
                    ResultSet rs;
                   
                       rs = stmt.executeQuery("desc atd;");
                       rs.last();
                       days = (rs.getRow()-6);
                       
                       String daynam[] = new String[days];
                       rs.absolute(6);
                       while(j<days && rs.next()){
                           daynam[j]=rs.getString("Field");
                           txt = txt+","+ daynam[j] ;
                       j++;
                       }
                        if(jRadioButton8.isSelected()){
                       txt+=" from atd where yr=1;";}
                       else{
                       txt+=" from atd where yr=2;";}    
                       rs = stmt.executeQuery(txt);
                      while(rs.next()){
                       j=0;num=0;
                       while(j<days){
                      if((rs.getString((++j)+6)).equals("P")) {
                               num++;
                           }
                                          
                        }
                       per = (num*100.0)/days;
                       if((per>=50.00)&&(per<60.00)){
                          Object obj[]={rs.getInt(1),rs.getInt(2),rs.getInt(3),rs.getString(4),rs.getString(5),rs.getString(6),per};
                          tm.addRow(obj);
                       }
                          
                      }
                   stmt.execute("Commit");
                    stmt.close();
                    con.close();
                }
                catch(Exception e){
                    op.showMessageDialog(this,e,"Connection Problem",0);
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    @SuppressWarnings("static-access")
    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
int days,num,j=0;
       double per;
       DefaultTableModel tm = (DefaultTableModel) tblg.getModel();
       tm.setRowCount(0);
       String txt = "Select yr,fltno,cdtno,regtno,iit,name";
        try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ncc","root","root");
                    Statement stmt = con.createStatement();
                    ResultSet rs;
                   
                       rs = stmt.executeQuery("desc atd;");
                       rs.last();
                       days = (rs.getRow()-6);
                       
                       String daynam[] = new String[days];
                       rs.absolute(6);
                       while(j<days && rs.next()){
                           daynam[j]=rs.getString("Field");
                           txt = txt+","+ daynam[j] ;
                       j++;
                       }
                        if(jRadioButton8.isSelected()){
                       txt+=" from atd where yr=1;";}
                       else{
                       txt+=" from atd where yr=2;";}    
                       rs = stmt.executeQuery(txt);
                      while(rs.next()){
                       j=0;num=0;
                       while(j<days){
                       if((rs.getString((++j)+6)).equals("P")){
                          num++;
                      }                   
                        }
                       per = (num*100.0)/days;
                       if((per<50.00)){
                          Object obj[]={rs.getInt(1),rs.getInt(2),rs.getInt(3),rs.getString(4),rs.getString(5),rs.getString(6),per};
                          tm.addRow(obj);
                       }
                          
                      }
                   stmt.execute("Commit");
                    stmt.close();
                    con.close();
                }
                catch(Exception e){
                    op.showMessageDialog(this,e,"Connection Problem",0);
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new start().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel alb;
    private javax.swing.JLabel as;
    private javax.swing.JLabel atdlbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JComboBox cbm;
    private javax.swing.JComboBox cby;
    private javax.swing.JTextField dat;
    private javax.swing.JTextField date;
    private javax.swing.JRadioButton drd;
    private javax.swing.JTextField flt;
    private javax.swing.JTextField flt1;
    private javax.swing.JTextField iitrno;
    private javax.swing.JTextField iitrno1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton mrd;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel nnd;
    private javax.swing.JOptionPane op;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel plb;
    private javax.swing.JLabel plbl;
    private javax.swing.JLabel plbl1;
    private javax.swing.JLabel plbl2;
    private javax.swing.JLabel pnd;
    private javax.swing.JLabel ps;
    private javax.swing.JPasswordField pwd1;
    private javax.swing.JTextField regt1;
    private javax.swing.JTextField regt2;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    private javax.swing.JTable tbl;
    private javax.swing.JTable tblg;
    private javax.swing.JLabel tlb;
    private javax.swing.JLabel ts;
    private javax.swing.JRadioButton yr1;
    private javax.swing.JRadioButton yr2;
    private javax.swing.JRadioButton yr3;
    private javax.swing.JRadioButton yr4;
    private javax.swing.JRadioButton yr5;
    private javax.swing.JRadioButton yr6;
    // End of variables declaration//GEN-END:variables
}
